name: base
channels:
- conda-forge
dependencies:
- python=3.11
- pytorch::pytorch=2.2.0=py3.11_cpu_0
- pip:
  - transformers[sklearn,sentencepiece,audio,vision]==4.37.2
  - sentence_transformers==2.2.2
  - torchvision==0.17.1
  - diffusers==0.26.3
  - accelerate==0.27.2
  - safetensors