name: "Build applications images"

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "dockerfiles/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  starlette-cpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      context: ./
      repository: huggingface
      image: hf-endpoints-inference-cpu
      dockerfile: dockerfiles/starlette/Dockerfile.cpu
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  starlette-gpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      context: ./
      repository: huggingface
      image: hf-endpoints-inference-gpu
      dockerfile: dockerfiles/starlette/Dockerfile.gpu
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
