name: "Build applications images"

on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - "src/**"
  #    - "dockerfiles/**"
  #    - "scripts/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  starlette-pytorch-cpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      image: inference-pytorch-cpu
      dockerfile: dockerfiles/pytorch/cpu/Dockerfile
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  starlette-pytorch-gpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      image: inference-pytorch-gpu
      dockerfile: dockerfiles/pytorch/gpu/Dockerfile
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  starlette-tensorflow-cpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      image: inference-tensorflow-cpu
      dockerfile: dockerfiles/tensorflow/cpu/Dockerfile
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  starlette-tensorflow-gpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      image: inference-tensorflow-gpu
      dockerfile: dockerfiles/tensorflow/gpu/Dockerfile
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
