name: "Build applications images"

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "dockerfiles/**"
      - "scripts/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  starlette-pytorch-cpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      image: inference-pytorch-cpu
      dockerfile: dockerfiles/pytorch/Dockerfile
      build_args: "BASE_IMAGE=ubuntu:22.04"
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  starlette-pytorch-gpu:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      image: inference-pytorch-gpu
      dockerfile: dockerfiles/pytorch/Dockerfile
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  starlette-pytorch-inf2:
    uses: ./.github/workflows/docker-build-action.yaml
    with:
      image: inference-pytorch-inf2
      dockerfile: dockerfiles/pytorch/Dockerfile
    secrets:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}