name: Run GPU Integration Tests

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
     - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytorch-integration-local:
    uses: ./.github/workflows/integration_test.yaml
    with:
      test_path: "tests/integ/test_pytorch_local_gpu.py"
      build_img_cmd: "make inference-pytorch-gpu"