name: GPU - Run Integration Tests

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  pytorch-integration-test:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: pip install -e .[test,dev,torch]
      - name: Build Docker
        run: docker build -t starlette-transformers:gpu -f dockerfiles/pytorch/gpu/Dockerfile .
      - name: Run Integration Tests
        run: RUN_SLOW=True make integ-test
  tensorflow-integration-test:
    needs:
      - pytorch-integration-test
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Uninstall pytorch
        run: pip uninstall torch torchvision -y
      - name: Install Python dependencies
        run: pip install -e .[test,dev,tensorflow]
      - name: Build Docker
        run: docker build -t starlette-transformers:gpu -f dockerfiles/tensorflow/gpu/Dockerfile .
      - name: Run Integration Tests
        run: RUN_SLOW=True make integ-test
  