name: Run GPU Integration Tests

on:
  push:
    branches:
     - main
  pull_request:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytorch-integration-local:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
      HF_HOME: /mnt/hf_cache/
      HF_HUB_CACHE: /mnt/hf_cache/hub
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - uses: actions/checkout@v4.1.1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Build
      run: make inference-pytorch-gpu
    - name: List images
      run: docker images
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install tox & uv
      run: pip install uv tox
    - name: Run local integration tests
      run: tox -e torch-integration-local-gpu -- -n 10
  pytorch-integration-remote:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Build
      run: make inference-pytorch-gpu
    - name: List images
      run: docker images
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install tox & uv
      run: pip install uv tox
    - name: Run remote integration tests
      run: tox -e torch-integration-remote-gpu -- -n 10