on:
  workflow_call:
    inputs:
      region:
        type: string
        required: false
        default: "us-east-1"
      hf_home:
        required: false
        type: string
        default: "/mnt/hf_cache/"
      hf_hub_cache:
        required: false
        type: string
        default: "/mnt/hf_cache/hub"
      run_slow:
        required: false
        type: string
        default: "True"
      test_path:
        type: string
        required: true
      test_parallelism:
        type: string
        required: false
        default: "4"
      build_img_cmd:
        type: string
        required: false
        default: "make inference-pytorch-gpu"
      log_level:
        type: string
        required: false
        default: "ERROR"
      log_format:
        type: string
        required: false
        default: "%(asctime)s %(levelname)s %(module)s:%(lineno)d %(message)s"
      runs_on:
        type: string
        required: false
        default: '["single-gpu", "nvidia-gpu", "t4", "ci"]'

jobs:
  pytorch-integration-tests:
    runs-on: ${{ fromJson(inputs.runs_on) }}
    env:
      AWS_REGION: ${{ inputs.region }}
      HF_HOME: ${{ inputs.hf_home }}
      HF_HUB_CACHE: ${{ inputs.hf_hub_cache }}
      RUN_SLOW: ${{ inputs.run_slow }}
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Build
      run: ${{ inputs.build_img_cmd }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: pip install ".[torch, test]"
    - name: Run local integration tests
      run: |
        python -m pytest \
        ${{ inputs.test_path }} -n ${{ inputs.test_parallelism }} \
        --log-cli-level='${{ inputs.log_level }}' \
        --log-format='${{ inputs.log_format }}'