name: Run Unit-Tests

on:
  push:
    branches:
     - main
  pull_request:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytorch-unit-test:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18
    - name: Install Tox & Dependencies
      run: pip install tox ".[test]"
    - name: Install FFMPEG
      run: |
        sudo apt-get update -y && sudo apt-get install -y ffmpeg
    - name: Run unit tests for Pytorch
      run: 	tox -e unit-torch-slow -- -n 4
  tensorflow-unit-test:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18
    - name: Install Tox & Dependencies
      run: pip install tox ".[test]"
    - name: Run unit tests for Tensorflow
      run: 	tox -e unit-tensorflow-slow -- -n 4