name: Run Unit-Tests

on:
  push:
    branches:
     - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytorch-unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18
    - name: Install Tox
      run: pip install tox
    - uses: Install FFMPEG
      run: |
        sudo apt-get update -y &&
        sudo apt-get upgrade -y &&
        sudo apt-get install -y ffmpeg
    - name: Run unit tests for Pytorch
      run: 	tox -e unit-torch-slow -- -n 4
  tensorflow-unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18
    - name: Install Tox
      run: pip install tox
    - name: Run unit tests for Tensorflow
      run: 	tox -e unit-tensorflow-slow -- -n 4