name: Run Unit-Tests

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
     - main
  pull_request:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytorch-unit-test:
    runs-on: 
      group: aws-g4dn-2xlarge-cache
    env:
      AWS_REGION: us-east-1
      CACHE_TEST_DIR: /mnt/hf_cache/hf-inference-toolkit-tests
      RUN_SLOW: True
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Copy unit tests to cache mount
      run: |
        sudo rm -rf ${{ env.CACHE_TEST_DIR }} && \
        sudo mkdir ${{ env.CACHE_TEST_DIR }} && \
        sudo chown -R runner ${{ env.CACHE_TEST_DIR }}
        cp -r tests ${{ env.CACHE_TEST_DIR }}
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Docker Build
      run: make inference-pytorch-gpu
    - name: Run unit tests
      run: |
        docker run \
          -e RUN_SLOW='${{ env.RUN_SLOW }}' \
          --gpus all \
          -e CACHE_TEST_DIR='${{ env.CACHE_TEST_DIR }}' \
          -v ./tests:${{ env.CACHE_TEST_DIR }} \
          --entrypoint /bin/bash \
          integration-test-pytorch:gpu \
          -c "pip install '.[test,st,diffusers,google]' && pytest ${{ env.CACHE_TEST_DIR }}/unit"
