name: Run Unit-Tests

on:
  push:
    branches:
     - main
  pull_request:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytorch-unit-test:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
    - name: Install CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-12-3
    - name: nvidia-smi
      run: nvidia-smi
    - uses: actions/checkout@v4.1.1
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.18
    - name: Install test dependencies
      run: pip install -U pip -r requirements-test.txt 
    - name: Install ffmpeg
      run: |
        sudo apt-get update -y && sudo apt-get install -y ffmpeg
    - name: Run unit tests for Pytorch
      run: 	tox -e unit-torch -- -n 4
  tensorflow-unit-test:
    runs-on: [single-gpu, nvidia-gpu, t4, ci]
    env:
      AWS_REGION: us-east-1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.18
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18
    - name: Install Tox & Dependencies
      run: pip install tox ".[test]"
    - name: Run unit tests for Tensorflow
      run: 	tox -e unit-tensorflow -- -n 4